import type { Course } from "@/lib/types";

export const courses: Course[] = [
  {
    slug: "cpr-aed-first-aid",
    name: "CPR/AED & First Aid",
    tagline: "Equip your team to respond confidently in cardiac and medical emergencies.",
    summary: "This hands-on, instructor-led course covers adult, child, and infant CPR, AED operation, and essential first aid skills. Participants practice on manikins and AED trainers so that when an emergency happens, response is instinctive — not hesitant.",
    heroImage: "https://picsum.photos/seed/cpr-course/800/500",
    durationLabel: "4 Hours",
    curriculum: [
      { title: "Recognizing a Life-Threatening Emergency", body: "Participants learn how to identify cardiac arrest, severe allergic reaction, choking, and other emergencies requiring immediate intervention." },
      { title: "Adult & Child CPR Technique", body: "Hands-on practice of compression depth, rate, and rescue breathing on CPR manikins. Covers single-rescuer and two-rescuer scenarios." },
      { title: "AED Operation", body: "Step-by-step operation of the workplace AED trainer: power on, electrode placement, rhythm analysis, and shock delivery." },
      { title: "Infant CPR & Choking Response", body: "Specialized techniques for infants including back blows, chest thrusts, and modified CPR." },
      { title: "Basic First Aid Skills", body: "Wound care, bleeding control, burn treatment, shock management, and recognition of stroke symptoms." },
    ],
    faqs: [
      { question: "Does this course provide certification?", answer: "Our training delivers skill-based competency in line with American Heart Association guidelines. Certificates of completion are issued. For roles requiring nationally accredited certification, please discuss specific credentialing requirements with our training coordinator." },
      { question: "How many employees can attend one session?", answer: "We recommend a maximum of 10–15 participants per instructor to ensure adequate hands-on practice time. Larger groups can be split across multiple sessions on the same day." },
    ],
    complianceTags: ["OSHA 1910.151", "AHA Guidelines"],
  },
  {
    slug: "active-shooter-response",
    name: "Active Shooter Response",
    tagline: "Practical, scenario-based training to help employees survive and assist others during an active threat.",
    summary: "Based on the Run-Hide-Fight framework, this course prepares employees to make fast, sound decisions during an active shooter or violent intruder event. Covers lockdown procedures, evacuation decision-making, tourniquet application, and communication with first responders.",
    heroImage: "https://picsum.photos/seed/active-shooter/800/500",
    durationLabel: "3 Hours",
    curriculum: [
      { title: "Situational Awareness & Threat Recognition", body: "Understanding pre-incident indicators and developing awareness habits that reduce response time." },
      { title: "Run — Evacuation Decision-Making", body: "When and how to evacuate safely, assembly points, and employee accountability." },
      { title: "Hide — Lockdown Procedures", body: "How to secure a space, barricade entry points, silence devices, and communicate silently with other employees." },
      { title: "Fight — Last Resort Defense", body: "Physical and improvised defensive actions as a last resort when escape is impossible." },
      { title: "Hemorrhage Control (Stop the Bleed)", body: "Application of direct pressure, wound packing, and commercial tourniquets to control life-threatening bleeding while awaiting EMS." },
      { title: "Communicating with First Responders", body: "What to say when calling 911, how to behave when law enforcement arrives, and providing information to help responders quickly." },
    ],
    faqs: [
      { question: "Is this training suitable for all employees?", answer: "Yes. The curriculum is designed for civilian workplaces and does not involve physical confrontation drills. Content is presented in a factual, non-alarmist manner appropriate for all staff." },
      { question: "Can this training be customized to our facility layout?", answer: "Absolutely. Our instructors review your facility's floor plan and tailor evacuation routes and lockdown scenarios to your specific environment." },
    ],
    complianceTags: ["Cal/OSHA SB 553", "FEMA Recommended"],
  },
  {
    slug: "bloodborne-pathogens",
    name: "Bloodborne Pathogens",
    tagline: "Required annual training for employees with potential exposure to blood or OPIM.",
    summary: "Mandatory under OSHA 29 CFR 1910.1030, this training covers the risks of HIV, Hepatitis B, and Hepatitis C transmission, proper use of PPE, exposure control procedures, and post-exposure steps. Delivered in plain language that fulfills your regulatory documentation requirement.",
    heroImage: "https://picsum.photos/seed/bbp/800/500",
    durationLabel: "2 Hours",
    curriculum: [
      { title: "Understanding Bloodborne Pathogens", body: "Modes of transmission for HIV, HBV, and HCV and which job roles carry exposure risk." },
      { title: "Exposure Control Plan", body: "Reviewing and understanding your facility's written Exposure Control Plan (ECP) as required by OSHA." },
      { title: "Universal Precautions & PPE", body: "Proper selection, donning, doffing, and disposal of gloves, masks, face shields, and gowns." },
      { title: "Engineering & Work-Practice Controls", body: "Sharps containers, hand hygiene protocols, and safe handling of contaminated materials." },
      { title: "Post-Exposure Protocol", body: "Immediate steps after a needlestick or splash incident, medical evaluation, and OSHA recordkeeping requirements." },
    ],
    faqs: [
      { question: "How often is this training required?", answer: "OSHA requires annual retraining for all employees with potential exposure. Training records must be retained for three years." },
    ],
    complianceTags: ["OSHA 1910.1030", "Cal/OSHA Required"],
  },
  {
    slug: "earthquake-disaster-preparedness",
    name: "Earthquake & Disaster Preparedness",
    tagline: "Get your team ready before the next California earthquake — not after.",
    summary: "California employers have a unique responsibility to prepare for seismic events. This course covers drop-cover-hold-on procedures, building evacuation protocols, post-earthquake safety assessment, and how to activate your Emergency Action Plan effectively.",
    heroImage: "https://picsum.photos/seed/earthquake/800/500",
    durationLabel: "2.5 Hours",
    curriculum: [
      { title: "California Seismic Risk & Your Workplace", body: "Overview of fault lines across the five-county region and how building type affects risk." },
      { title: "Drop, Cover, and Hold On", body: "Proper technique and common myths about earthquake protective actions." },
      { title: "Post-Earthquake Building Assessment", body: "Visual inspection checklist for structural damage, gas leaks, electrical hazards, and other post-event risks before re-entering." },
      { title: "Emergency Action Plan Activation", body: "Roles and responsibilities, employee accountability, and coordinating with local emergency services." },
      { title: "72-Hour Self-Sufficiency", body: "Why infrastructure failures can take days to repair and how workplace emergency kits bridge that gap." },
    ],
    faqs: [
      { question: "Is this training required by Cal/OSHA?", answer: "Cal/OSHA requires employers to have a written Emergency Action Plan (8 CCR 3220) and an Injury and Illness Prevention Program. Providing training that supports these plans is a practical compliance step." },
    ],
    complianceTags: ["Cal/OSHA 8 CCR 3220", "FEMA Recommended"],
  },
  {
    slug: "fire-extinguisher-safety",
    name: "Fire Extinguisher Safety",
    tagline: "Know your fire classes, your extinguisher types, and how to use PASS — before you need to.",
    summary: "OSHA requires that employees who are expected to use portable fire extinguishers receive training. This hands-on course covers fire chemistry, extinguisher selection, and live-fire PASS technique (where permitted by local fire authority).",
    heroImage: "https://picsum.photos/seed/fire-ext/800/500",
    durationLabel: "2 Hours",
    curriculum: [
      { title: "Fire Triangle & Fire Classes", body: "A, B, C, D, and K fire classes and the common ignition sources for each." },
      { title: "Extinguisher Types & Selection", body: "Matching the right extinguisher to the fire class and identifying your workplace's extinguisher locations." },
      { title: "PASS Technique — Pull, Aim, Squeeze, Sweep", body: "Step-by-step instruction and hands-on drill using inert training extinguishers." },
      { title: "Evacuation vs. Suppression Decision", body: "When it is safe to attempt suppression and when evacuation is the correct response." },
    ],
    faqs: [
      { question: "Is this OSHA required?", answer: "Yes, OSHA 29 CFR 1910.157(g) requires annual hands-on training for employees designated to use portable fire extinguishers." },
    ],
    complianceTags: ["OSHA 1910.157", "Cal/OSHA Required"],
  },
  {
    slug: "forklift-certification",
    name: "Forklift Certification",
    tagline: "OSHA-mandated operator training for powered industrial trucks in your facility.",
    summary: "OSHA 29 CFR 1910.178 requires that every forklift operator be evaluated and certified by their employer. Our instructor-led program covers pre-operation inspection, load handling, pedestrian safety, and a practical skills evaluation — all documented to meet OSHA's certification recordkeeping standard.",
    heroImage: "https://picsum.photos/seed/forklift/800/500",
    durationLabel: "8 Hours",
    curriculum: [
      { title: "Forklift Hazards & OSHA Requirements", body: "Overview of powered industrial truck injuries and the regulatory framework governing training and certification." },
      { title: "Pre-Operation Inspection", body: "Daily inspection checklist: tires, forks, mast, hydraulics, brakes, and steering." },
      { title: "Controls & Instrumentation", body: "Operating controls, load capacity placards, and stability triangle concepts." },
      { title: "Load Handling & Stacking", body: "Center of gravity management, load stability, and safe stacking heights." },
      { title: "Pedestrian Safety & Traffic Patterns", body: "Right-of-way procedures, blind-corner protocols, and pedestrian awareness." },
      { title: "Practical Skills Evaluation", body: "Supervised on-site operating evaluation with documented results per OSHA's certification recordkeeping requirements." },
    ],
    faqs: [
      { question: "How often must operators be re-evaluated?", answer: "OSHA requires re-evaluation every three years, or sooner if an operator is observed operating unsafely, after an incident, or when assigned to a different type of truck." },
    ],
    complianceTags: ["OSHA 1910.178", "Cal/OSHA Required"],
  },
  {
    slug: "hazwoper",
    name: "Hazwoper",
    tagline: "OSHA-required hazardous waste operations and emergency response training.",
    summary: "Required under OSHA 29 CFR 1910.120, HAZWOPER training is mandatory for employees involved in clean-up operations, emergency response to hazardous substance releases, or work at treatment/storage/disposal facilities. We offer initial 40-hour, 24-hour, and 8-hour annual refresher programs.",
    heroImage: "https://picsum.photos/seed/hazwoper/800/500",
    durationLabel: "8–40 Hours",
    curriculum: [
      { title: "Regulatory Overview & HAZWOPER Applicability", body: "Who must comply, what operations are covered, and the employer's obligations under 29 CFR 1910.120." },
      { title: "Hazard Recognition & Toxicology Basics", body: "Identifying chemical hazards, reading SDS/MSDS, and understanding routes of exposure." },
      { title: "Personal Protective Equipment Selection", body: "Levels A–D protection, PPE selection criteria, donning/doffing, and heat stress management." },
      { title: "Site Control & Safety Planning", body: "Work zones, decontamination procedures, buddy system, and air monitoring basics." },
      { title: "Emergency Response Procedures", body: "Spill response, notification requirements, evacuation, and coordination with HAZMAT teams." },
    ],
    faqs: [
      { question: "Do you offer the full 40-hour initial training on-site?", answer: "Yes. We can conduct the 40-hour initial training at your facility over five consecutive days or in a split schedule. Contact us to discuss your timeline." },
    ],
    complianceTags: ["OSHA 1910.120", "Cal/OSHA Required"],
  },
  {
    slug: "respirator-fit-testing",
    name: "Respirator Fit Testing",
    tagline: "OSHA-compliant qualitative and quantitative fit testing for tight-fitting respirators.",
    summary: "OSHA 29 CFR 1910.134 requires medical clearance, proper training, and annual fit testing for all employees required to wear tight-fitting respirators. Our certified technicians conduct QLFT (qualitative) and QNFT (quantitative) testing and provide documented results for your compliance records.",
    heroImage: "https://picsum.photos/seed/fit-test/800/500",
    durationLabel: "1–2 Hours",
    curriculum: [
      { title: "Medical Evaluation Overview", body: "Review of the OSHA medical questionnaire process required prior to respirator use." },
      { title: "Respirator Types & Selection", body: "Half-face, full-face, powered air-purifying, and supplied-air respirators — when each is required." },
      { title: "Donning, Doffing & Seal Checks", body: "Positive and negative seal check procedures and common donning errors." },
      { title: "Qualitative Fit Testing (QLFT)", body: "Saccharin or Bitrex challenge testing using the OSHA-accepted QLFT protocol." },
      { title: "Documentation & Recordkeeping", body: "Completing fit-test records per OSHA's mandatory written records standard." },
    ],
    faqs: [
      { question: "How often is fit testing required?", answer: "At least annually, and also when an employee has a significant change in facial features (weight change, dental work, etc.) or changes to a different respirator model." },
    ],
    complianceTags: ["OSHA 1910.134", "Cal/OSHA Required"],
  },
  {
    slug: "osha-compliance",
    name: "OSHA Compliance Training",
    tagline: "Understand your OSHA obligations before an inspection — not after.",
    summary: "Designed for safety officers, HR managers, and facility managers, this course provides a practical overview of the OSHA standards most commonly cited in SoCal workplaces. Covers record-keeping, posting requirements, hazard communication, and how to prepare for an OSHA inspection.",
    heroImage: "https://picsum.photos/seed/osha-compliance/800/500",
    durationLabel: "4 Hours",
    curriculum: [
      { title: "OSHA Structure & Enforcement Authority", body: "Federal vs. Cal/OSHA, how inspections are triggered, and employer rights during an inspection." },
      { title: "Injury & Illness Prevention Program (IIPP)", body: "Cal/OSHA's IIPP requirement, what the program must include, and how to document it." },
      { title: "Hazard Communication (HazCom / GHS)", body: "SDS management, container labeling, and training documentation requirements." },
      { title: "Recordkeeping: Forms 300, 300A, 301", body: "What to record, what is exempt, electronic reporting, and posting deadlines." },
      { title: "Top Cal/OSHA Citations & How to Avoid Them", body: "A walkthrough of the most frequently cited standards in Los Angeles, San Diego, and Orange County and practical corrective steps." },
    ],
    faqs: [],
    complianceTags: ["Cal/OSHA", "OSHA Compliant"],
  },
  {
    slug: "workplace-safety",
    name: "Workplace Safety",
    tagline: "Building a culture of safety that reduces incidents and keeps your team on the job.",
    summary: "A broad-based safety orientation for new hires and annual refresher for existing staff. Covers hazard identification, reporting, lockout/tagout basics, slip-trip-fall prevention, and emergency response procedures specific to your workplace.",
    heroImage: "https://picsum.photos/seed/workplace-safety/800/500",
    durationLabel: "3 Hours",
    curriculum: [
      { title: "Hazard Identification & Reporting", body: "How to recognize and report unsafe conditions, near-misses, and first-aid incidents." },
      { title: "Slip, Trip & Fall Prevention", body: "Common causes of STF incidents and workplace controls to eliminate them." },
      { title: "Lockout/Tagout Awareness", body: "The purpose of LOTO procedures and employee responsibilities when maintenance is in progress." },
      { title: "Emergency Action Plan Overview", body: "Evacuation routes, assembly points, and role of emergency wardens in your facility." },
    ],
    faqs: [],
    complianceTags: ["OSHA 1910.132", "Cal/OSHA Compliant"],
  },
  {
    slug: "workplace-violence-de-escalation",
    name: "Workplace Violence & De-Escalation",
    tagline: "Recognize warning signs and resolve conflict before it becomes a crisis.",
    summary: "Required under California SB 553 for most employers effective July 2024, this training addresses identifying threatening behavior, de-escalation techniques, and your facility's Workplace Violence Prevention Plan (WVPP). Delivered in a scenario-based format relevant to your industry.",
    heroImage: "https://picsum.photos/seed/wv-deescalation/800/500",
    durationLabel: "2 Hours",
    curriculum: [
      { title: "Types of Workplace Violence", body: "Type I–IV classification (criminal intent, customer, worker-on-worker, personal) and the situations that produce each." },
      { title: "Behavioral Warning Signs", body: "Escalating indicators and how to document and report them through your Workplace Violence Prevention Plan." },
      { title: "De-Escalation Techniques", body: "Verbal and non-verbal strategies for calming an agitated individual, setting limits, and creating distance." },
      { title: "Your Workplace Violence Prevention Plan", body: "Review of your facility's WVPP, reporting procedures, and employee protections against retaliation." },
    ],
    faqs: [
      { question: "Is this training required under California law?", answer: "Yes. California SB 553, effective July 1, 2024, requires most California employers to establish a Workplace Violence Prevention Plan and provide training to all employees annually." },
    ],
    complianceTags: ["Cal/OSHA SB 553", "California Required"],
  },
  {
    slug: "heat-injury-illness-prevention",
    name: "Heat Injury & Illness Prevention",
    tagline: "California's outdoor and indoor heat illness regulations — training that keeps people working safely.",
    summary: "Cal/OSHA's heat illness prevention regulations (8 CCR 3395) require specific training for all employees working in heat conditions. This course covers the causes of heat illness, early warning signs, hydration and rest requirements, and emergency response procedures.",
    heroImage: "https://picsum.photos/seed/heat-illness/800/500",
    durationLabel: "1.5 Hours",
    curriculum: [
      { title: "Understanding Heat Illness", body: "Heat cramps, heat exhaustion, and heat stroke — how they progress and why rapid response matters." },
      { title: "Cal/OSHA Requirements for Employers", body: "Water, shade, rest periods, acclimatization procedures, and high-heat protocols for days above 95°F." },
      { title: "Employee Roles & Responsibilities", body: "Recognizing symptoms in yourself and co-workers and the right of employees to request shade and water." },
      { title: "Emergency Response to Heat Stroke", body: "Activating emergency services, cooling techniques, and first aid until EMS arrives." },
    ],
    faqs: [
      { question: "Does this apply to indoor workers?", answer: "Yes. Cal/OSHA amended regulations in 2024 to include indoor workplaces where temperatures reach 82°F. Training requirements apply to both indoor and outdoor workers." },
    ],
    complianceTags: ["Cal/OSHA 8 CCR 3395", "California Required"],
  },
  {
    slug: "sexual-harassment-prevention",
    name: "Sexual Harassment Prevention",
    tagline: "California-compliant training that meets SB 1343 requirements for supervisory and non-supervisory employees.",
    summary: "California law (SB 1343/AB 1825) requires employers with five or more employees to provide sexual harassment prevention training: 2 hours for supervisors and 1 hour for all other employees, every two years. Our training is interactive, scenario-based, and delivered by a qualified instructor.",
    heroImage: "https://picsum.photos/seed/harassment-prev/800/500",
    durationLabel: "1–2 Hours",
    curriculum: [
      { title: "Definition of Sexual Harassment", body: "Quid pro quo and hostile work environment harassment — legal definitions and real-world examples." },
      { title: "California Law & Employer Liability", body: "FEHA, Title VII, and the specific California standards that create strict employer liability." },
      { title: "Bystander Intervention", body: "Practical strategies for employees to safely interrupt harassing behavior and support affected coworkers." },
      { title: "Reporting & Investigation Procedures", body: "How to use your company's complaint procedure, external reporting channels (DFEH/EEOC), and anti-retaliation protections." },
    ],
    faqs: [
      { question: "Does this meet California's SB 1343 requirement?", answer: "Yes. Our instructor-led training is delivered by a qualified trainer as defined under SB 1343 and AB 1825, and we provide attendance records and completion certificates for your documentation." },
    ],
    complianceTags: ["SB 1343", "AB 1825", "FEHA Compliant"],
  },
];
