import type { Industry } from "@/lib/types";

export const industries: Industry[] = [
  {
    slug: "offices",
    name: "Offices",
    headline: "Keep your team safe and your building OSHA-compliant — without adding to your HR team's plate.",
    body: "Office environments carry real OSHA obligations that are easy to overlook: mandatory first aid supplies per employee count, bloodborne pathogen training for any designated responder, and emergency action plans that cover the whole building. UniShield makes compliance routine — stocked cabinets, trained staff, and documentation ready when an inspector arrives.",
    heroImage: "https://picsum.photos/seed/office-industry/800/500",
    painPoints: [
      "OSHA first aid cabinet requirements scale with headcount — easy to fall behind after hiring",
      "Bloodborne pathogen training is annual and must be documented per employee",
      "Emergency Action Plans require employee training that gets delayed without a vendor to schedule it",
      "Expired supplies in cabinets are an immediate OSHA citation if inspected",
    ],
    relatedProducts: ["first-aid-cabinets-kits", "first-aid-restocking-supplies"],
    relatedServices: ["first-aid-restocking", "training-compliance"],
    relatedCourses: ["bloodborne-pathogens", "cpr-aed-first-aid"],
  },
  {
    slug: "schools",
    name: "Schools & Educational Institutions",
    headline: "Students, staff, and visitors depend on you to be prepared. UniShield helps you stay ready.",
    body: "Schools face a wide range of emergency scenarios — from playground injuries to active threats — and must maintain compliance across multiple OSHA and Title 22 requirements simultaneously. UniShield works with K-12 schools, community colleges, and universities across Los Angeles, Orange, and San Diego counties.",
    heroImage: "https://picsum.photos/seed/school-industry/800/500",
    painPoints: [
      "Multiple buildings require multiple stocked cabinets — hard to track without a service partner",
      "AED placement requirements mandate devices in specific locations and documented maintenance",
      "Active shooter and lockdown drills must be documented annually per California law",
      "Large staff turnover means CPR/AED training certification lapses frequently",
    ],
    relatedProducts: ["first-aid-cabinets-kits", "aed-supplies"],
    relatedServices: ["first-aid-restocking", "aed-maintenance"],
    relatedCourses: ["cpr-aed-first-aid", "active-shooter-response"],
  },
  {
    slug: "restaurants",
    name: "Restaurants & Food Service",
    headline: "Fast-paced kitchens and high staff turnover make compliance harder — and more important.",
    body: "Restaurant environments have elevated injury risk: burns, cuts, slip-and-fall, and foodborne illness response. Cal/OSHA enforces first aid requirements in food service as vigorously as in any other industry. UniShield keeps your kitchen-area cabinets stocked, your managers CPR-trained, and your bloodborne pathogen documentation current.",
    heroImage: "https://picsum.photos/seed/restaurant-industry/800/500",
    painPoints: [
      "High staff turnover means training records lapse constantly",
      "Kitchen injuries require well-stocked burn care and wound treatment supplies",
      "Bloodborne pathogen training is mandatory for any employee who may be exposed to blood — which includes line cooks handling injuries",
      "Health department inspections increasingly check first aid compliance",
    ],
    relatedProducts: ["first-aid-cabinets-kits", "first-aid-restocking-supplies"],
    relatedServices: ["first-aid-restocking", "training-compliance"],
    relatedCourses: ["bloodborne-pathogens", "cpr-aed-first-aid"],
  },
  {
    slug: "medical-dental",
    name: "Medical & Dental Offices",
    headline: "Your patients expect clinical-grade safety. Your compliance obligations do too.",
    body: "Medical and dental offices operate under both OSHA and California Department of Public Health requirements. Bloodborne pathogen programs, sharps management, and employee training must be rigorously documented. UniShield supports your compliance program with regular service visits and training that satisfies both federal and state standards.",
    heroImage: "https://picsum.photos/seed/medical-industry/800/500",
    painPoints: [
      "OSHA bloodborne pathogen standards require annual training and a written Exposure Control Plan",
      "PPE inventory must match exposure risks — not just what's on hand",
      "Sharps container management and disposal records must be maintained",
      "Staff CPR certification lapses are a liability risk in a patient-facing environment",
    ],
    relatedProducts: ["ppe", "first-aid-restocking-supplies"],
    relatedServices: ["training-compliance", "first-aid-restocking"],
    relatedCourses: ["bloodborne-pathogens", "cpr-aed-first-aid"],
  },
  {
    slug: "shops-factories",
    name: "Shops & Factories",
    headline: "Industrial hazards demand industrial-grade compliance. UniShield delivers both.",
    body: "Manufacturing, fabrication, and warehouse environments face the broadest range of OSHA requirements: first aid, PPE, lockout/tagout, eyewash, hazmat, forklift, and more. UniShield's multi-service program brings all of these compliance areas under one roof so your safety officer can focus on preventing incidents rather than chasing vendors.",
    heroImage: "https://picsum.photos/seed/factory-industry/800/500",
    painPoints: [
      "Eyewash stations must be within 10 seconds of hazardous chemical areas per ANSI Z358.1",
      "Forklift operators must be evaluated and certified by the employer — not just trained",
      "PPE selection must be based on a documented hazard assessment",
      "HAZWOPER training is mandatory for any employee involved in hazmat cleanup or emergency response",
    ],
    relatedProducts: ["eye-wash-stations", "ppe", "first-aid-cabinets-kits"],
    relatedServices: ["eyewash-station-service", "fire-protection", "facility-services"],
    relatedCourses: ["forklift-certification", "hazwoper", "respirator-fit-testing"],
  },
  {
    slug: "film-industry",
    name: "Film & Entertainment Industry",
    headline: "Production sets move fast and span multiple locations. Your safety program has to keep up.",
    body: "Film productions, commercial shoots, and live events carry unique occupational hazards: stunt work, pyrotechnics, electrical rigging, remote locations, and constantly rotating crews. UniShield supplies portable safety kits and on-site first aid support for productions across Los Angeles and surrounding counties, and our training programs satisfy the union-required safety bulletins that production companies must document.",
    heroImage: "https://picsum.photos/seed/film-industry/800/500",
    painPoints: [
      "Production locations change daily — portable first aid solutions are essential",
      "Large rotating crews mean CPR/AED training must reach a constantly changing workforce",
      "Union safety bulletins require specific training records for productions",
      "Remote or outdoor locations may require disaster and emergency preparedness planning",
    ],
    relatedProducts: ["first-aid-cabinets-kits", "disaster-survival-kits", "ppe"],
    relatedServices: ["training-compliance", "facility-services"],
    relatedCourses: ["cpr-aed-first-aid", "active-shooter-response", "heat-injury-illness-prevention"],
  },
];
