import type { Service } from "@/lib/types";

export const services: Service[] = [
  {
    slug: "first-aid-restocking",
    name: "First Aid Cabinet Restocking",
    summary: "Scheduled, documented restocking of your first aid cabinets — so you're always OSHA-compliant, always ready.",
    description: "Our most popular service. A UniShield technician visits your facility on a scheduled cadence, inspects every first aid cabinet, replaces expired or depleted supplies, and provides a signed compliance report. You get peace of mind and a paper trail for OSHA inspections — all without pulling anyone off your payroll to manage supplies.",
    heroImage: "https://picsum.photos/seed/restocking-service/800/500",
    bullets: [
      "Scheduled monthly, quarterly, or custom cadence",
      "Full inspection and restock of all cabinets on each visit",
      "Supplies replaced with ANSI Z308.1-compliant products",
      "Signed compliance report with technician's findings",
      "Expiration date tracking with proactive replacement",
      "No surprise charges — clear, flat-rate service agreement",
    ],
    faqs: [],
  },
  {
    slug: "eyewash-station-service",
    name: "Eye Wash Station Servicing",
    summary: "ANSI Z358.1 requires weekly eyewash activation and annual inspection. We handle both.",
    description: "ANSI Z358.1 mandates that plumbed eyewash stations be activated weekly to flush stagnant water and that self-contained units be refilled and inspected regularly. Non-compliance can result in Cal/OSHA citations and, more importantly, leaves employees vulnerable in a chemical splash emergency. UniShield's eyewash service program covers weekly activation (or documentation support), annual inspection, water quality maintenance, and supply replenishment.",
    heroImage: "https://picsum.photos/seed/eyewash-service/800/500",
    bullets: [
      "Weekly activation and water flush per ANSI Z358.1",
      "Portable unit refills with fresh, buffered saline solution",
      "Annual formal inspection with documented results",
      "Replacement of worn heads, dust covers, and signage",
      "Plumbed and portable station service available",
      "Compliance report provided after each visit",
    ],
    faqs: [],
  },
  {
    slug: "aed-maintenance",
    name: "AED Maintenance & Management",
    summary: "Keep your AED ready to save a life — routine maintenance, battery replacement, and compliance tracking.",
    description: "An AED that fails in an emergency is worse than no AED at all — because someone will reach for it. Our AED maintenance program ensures your unit stays in ready status through scheduled inspections, proactive battery and pad replacement, and a compliance calendar that tells you what's due before it expires. We work with all major AED brands on the market.",
    heroImage: "https://picsum.photos/seed/aed-maintenance/800/500",
    bullets: [
      "Annual AED inspection and function test",
      "Proactive replacement of pads and batteries before expiration",
      "Compliance calendar with email reminders",
      "AED registration and local EMS notification support",
      "Rescue kit resupply (CPR mask, gloves, razor, trauma shears)",
      "All major brands supported (Philips, Zoll, Defibtech, Cardiac Science)",
    ],
    faqs: [],
  },
  {
    slug: "training-compliance",
    name: "Training & Compliance Management",
    summary: "Ongoing coordination of your employee safety training schedule, records, and renewal tracking.",
    description: "Staying ahead of mandatory training deadlines across a growing workforce is a full-time job. Our Training & Compliance Management service assigns you a dedicated coordinator who tracks completion records, schedules refresher courses before deadlines, and provides documentation for OSHA and Cal/OSHA compliance audits. Covers CPR/AED, bloodborne pathogens, heat illness, sexual harassment, and more.",
    heroImage: "https://picsum.photos/seed/training-mgmt/800/500",
    bullets: [
      "Dedicated compliance coordinator for your account",
      "Training calendar with renewal reminders",
      "Digital storage of all completion certificates and attendance records",
      "Scheduling of on-site instructor-led sessions",
      "Coverage for all Cal/OSHA and California-mandated training",
      "Annual compliance summary report for management review",
    ],
    faqs: [],
  },
  {
    slug: "fire-protection",
    name: "Fire Protection Services",
    summary: "Fire extinguisher inspection, recharge, and hydrostatic testing — all backed by documentation.",
    description: "OSHA 29 CFR 1910.157 and NFPA 10 require annual inspection of portable fire extinguishers and periodic hydrostatic testing. UniShield's fire protection service covers annual visual inspections, pressure testing, recharging, and 6-year maintenance. We tag each unit and provide a signed service report that satisfies both OSHA and Cal/OSHA inspectors.",
    heroImage: "https://picsum.photos/seed/fire-protection/800/500",
    bullets: [
      "Annual visual inspection per NFPA 10 and OSHA 1910.157",
      "Recharge and refill of discharged or depleted extinguishers",
      "6-year internal maintenance and 12-year hydrostatic testing",
      "Placement review and quantity compliance check",
      "Inspection tags and compliance documentation",
      "Emergency replacement units available",
    ],
    faqs: [],
  },
  {
    slug: "facility-services",
    name: "Facility Safety Services",
    summary: "A bundled safety program covering multiple compliance areas under one service agreement.",
    description: "For facilities that want a single partner to handle multiple safety obligations, our Facility Services program bundles first aid restocking, eyewash servicing, AED maintenance, and training compliance into one coordinated annual contract. One invoice, one point of contact, and a comprehensive compliance calendar — so nothing slips through the cracks.",
    heroImage: "https://picsum.photos/seed/facility-services/800/500",
    bullets: [
      "Single point of contact for all safety services",
      "Bundled first aid, eyewash, AED, and training management",
      "One annual contract with consolidated billing",
      "Master compliance calendar tracking all deadlines",
      "Priority scheduling during high-demand periods",
      "Annual safety program review with recommendations",
    ],
    faqs: [],
  },
];
